---
- name: Configure the external frontends
  become: True
  template:
    src: frontend.conf.j2
    dest: /etc/haproxy/conf.d/70-frontend.conf
    owner: root
    group: root
    mode: 0640

- name: Configure the Kubernetes API backends
  become: True
  template:
    src: 80-backend.conf.j2
    dest: /etc/haproxy/conf.d/80-backend.conf
    owner: root
    group: root
    mode: 0640
